# -*- coding: utf-8 -*-
"""MachinLearning_Iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1InqwrFFTiJQYHAMPqOR0c2CaVM6tQ3wZ
"""

from sklearn.datasets import load_iris
iris_dataset = load_iris()

# load_iris가 반환한 iris 객체는 파이썬의 딕셔너리와 유사한 Bunch 클래스의 객체( 키와 값으로 구성됨)

print(iris_dataset.keys())

print(iris_dataset["DESCR"][:193])

print(iris_dataset["target_names"]) # 예측하려는 붓꽃 품종의 이름/문자열 배열

print(iris_dataset["feature_names"]) # 각 특성을 설명하는 문자열 리스트

type(iris_dataset["data"])

iris_dataset["data"].shape # 데이터의 크기

# 이 배열은 150개의 붓꽃 데이터를 가짐 
# 각 아이템은 샘플이라고 함 / 속성은 특성이라고 함
# data 배열의 크기는 샘플의 수에 특성 수를 곱한 값

iris_dataset['data'][:5]

# target은 각 원소가 붓꽃 하나에 해당하는 1차원 배열

type(iris_dataset["target"])

iris_dataset["target"].shape

iris_dataset["target"]

