# -*- coding: utf-8 -*-
"""Numpy_descriptive statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14wsExzs1r4NOU1fuMvnv7GOzOv-jFL_5
"""

import numpy as np

a = np.array([[1,2,3,4], [46,99,100,71], [81,59,90,100]])

print(a)

b = a[1].argsort()
print(b)

a[:,b]

# 3.4 기술 통계

# 넘파이는 다음과 같은 데이터 집합에 대해 간단한 통계를 계산하는 함수를 제공
# 기술 통계(descriptive statistics)



# 데이터의 개수(count)
# 평균(mean, average)
# 분산(variance)
# 표준 편차(standard deviation)
# 최댓값(maximum)
# 최솟값(minimu,)
# 중앙값(median)
# 사분위수(quartile)

